import { PlayerProp, Alert, GameStat } from "./types";

export const MOCK_PROPS: PlayerProp[] = [
  {
    id: "1",
    player: "LeBron James",
    playerName: "LeBron James",
    playerInitials: "LJ",
    tier: "S",
    playType: "OVER",
    propType: "pts",
    line: 24.5,
    projectedPts: 28.2,
    projection: 28.2,
    diff: 3.7,
    bookLine: 24.5,
    aiProj: 28.2,
    edge: 3.7,
    confidence: 88,
    confidenceDisplay: "88%",
    matchup: "Lakers vs Knicks",
    category: "Points",
    score: 45,
    team: "LAL",
    opponent: "NYK",
    hitRateL10: 80,
    hitRateDisplay: "80%",
    algoRecord: "10-5",
    modelRecord: "12-3",
    lastResult: "HIT",
    algoModelBlend: 85,
    tierRank: 1,
    last10Games: [25, 28, 22, 30, 27, 29, 24, 31, 26, 28],
    g1: 25, g2: 28, g3: 22, g4: 30, g5: 27, g6: 29, g7: 24, g8: 31, g9: 26, g10: 28,
    edgeDisplay: "+3.7 pts",
    valueLabel: "High Value",
    isHighValue: true,
  },
  {
    id: "2",
    player: "Stephen Curry",
    playerName: "Stephen Curry",
    playerInitials: "SC",
    tier: "S",
    playType: "OVER",
    propType: "pts",
    line: 4.5,
    projectedPts: 5.8,
    projection: 5.8,
    diff: 1.3,
    bookLine: 4.5,
    aiProj: 5.8,
    edge: 1.3,
    confidence: 92,
    confidenceDisplay: "92%",
    matchup: "Warriors vs Suns",
    category: "3-Pointers",
    score: 50,
    team: "GSW",
    opponent: "PHX",
    hitRateL10: 90,
    hitRateDisplay: "90%",
    algoRecord: "15-2",
    modelRecord: "14-3",
    lastResult: "HIT",
    algoModelBlend: 92,
    tierRank: 2,
    last10Games: [5, 6, 4, 7, 5, 6, 4, 8, 5, 6],
    g1: 5, g2: 6, g3: 4, g4: 7, g5: 5, g6: 6, g7: 4, g8: 8, g9: 5, g10: 6,
    edgeDisplay: "+1.3 pts",
    valueLabel: "High Value",
    isHighValue: true,
  },
  {
    id: "3",
    player: "Nikola Jokic",
    playerName: "Nikola Jokic",
    playerInitials: "NJ",
    tier: "A",
    playType: "OVER",
    propType: "pts",
    line: 12.5,
    projectedPts: 13.8,
    projection: 13.8,
    diff: 1.3,
    bookLine: 12.5,
    aiProj: 13.8,
    edge: 1.3,
    confidence: 76,
    confidenceDisplay: "76%",
    matchup: "Nuggets vs Mavericks",
    category: "Rebounds",
    score: 35,
    team: "DEN",
    opponent: "DAL",
    hitRateL10: 70,
    hitRateDisplay: "70%",
    algoRecord: "8-7",
    modelRecord: "9-6",
    lastResult: "MISS",
    algoModelBlend: 75,
    tierRank: 3,
    last10Games: [14, 12, 15, 11, 13, 14, 12, 16, 13, 14],
    g1: 14, g2: 12, g3: 15, g4: 11, g5: 13, g6: 14, g7: 12, g8: 16, g9: 13, g10: 14,
    edgeDisplay: "+1.3 pts",
    valueLabel: "Medium Value",
    isHighValue: false,
  },
  {
    id: "4",
    player: "Luka Doncic",
    playerName: "Luka Doncic",
    playerInitials: "LD",
    tier: "B",
    playType: "OVER",
    propType: "pts",
    line: 9.5,
    projectedPts: 10.2,
    projection: 10.2,
    diff: 0.7,
    bookLine: 9.5,
    aiProj: 10.2,
    edge: 0.7,
    confidence: 64,
    confidenceDisplay: "64%",
    matchup: "Mavericks vs Nuggets",
    category: "Assists",
    score: 25,
    team: "DAL",
    opponent: "DEN",
    hitRateL10: 60,
    hitRateDisplay: "60%",
    algoRecord: "7-8",
    modelRecord: "8-7",
    lastResult: "HIT",
    algoModelBlend: 65,
    tierRank: 4,
    last10Games: [10, 9, 11, 8, 10, 11, 9, 12, 10, 11],
    g1: 10, g2: 9, g3: 11, g4: 8, g5: 10, g6: 11, g7: 9, g8: 12, g9: 10, g10: 11,
    edgeDisplay: "+0.7 pts",
    valueLabel: "Medium Value",
    isHighValue: false,
  },
  {
    id: "5",
    player: "Giannis Antetokounmpo",
    playerName: "Giannis Antetokounmpo",
    playerInitials: "GA",
    tier: "S",
    playType: "OVER",
    propType: "pts",
    line: 30.5,
    projectedPts: 33.1,
    projection: 33.1,
    diff: 2.6,
    bookLine: 30.5,
    aiProj: 33.1,
    edge: 2.6,
    confidence: 81,
    confidenceDisplay: "81%",
    matchup: "Bucks vs Celtics",
    category: "Points",
    score: 40,
    team: "MIL",
    opponent: "BOS",
    hitRateL10: 80,
    hitRateDisplay: "80%",
    algoRecord: "11-4",
    modelRecord: "10-5",
    lastResult: "HIT",
    algoModelBlend: 82,
    tierRank: 5,
    last10Games: [32, 35, 28, 34, 31, 33, 29, 36, 32, 34],
    g1: 32, g2: 35, g3: 28, g4: 34, g5: 31, g6: 33, g7: 29, g8: 36, g9: 32, g10: 34,
    edgeDisplay: "+2.6 pts",
    valueLabel: "High Value",
    isHighValue: true,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "1",
    type: "alert",
    title: "High Value Pick: LeBron James",
    description: "AI identifies +3.7 edge on LeBron James Points prop.",
    timestamp: "2 min ago",
    isRead: false,
    isHighPriority: true,
  },
  {
    id: "2",
    type: "system",
    title: "System Update: Anthony Davis",
    description: "Davis (Foot) is OUT for tonight's game vs Knicks.",
    timestamp: "1 hr ago",
    isRead: false,
    isHighPriority: true,
  },
  {
    id: "3",
    type: "miss",
    title: "Line Move: Stephen Curry",
    description: "3PM line moved from 4.5 to 5.5 in the last hour.",
    timestamp: "3 hr ago",
    isRead: true,
    isHighPriority: false,
  },
  {
    id: "4",
    type: "hit",
    title: "Pick Won: Nikola Jokic",
    description: "Jokic cleared 12.5 REB with 15 boards tonight.",
    timestamp: "5 hr ago",
    isRead: true,
    isHighPriority: false,
  },
];

export const MOCK_GAME_STATS: GameStat[] = [
  { date: "2/15", value: 28, opponent: "GSW" },
  { date: "2/18", value: 22, opponent: "PHX" },
  { date: "2/20", value: 31, opponent: "DAL" },
  { date: "2/22", value: 19, opponent: "LAC" },
  { date: "2/25", value: 26, opponent: "MEM" },
  { date: "2/27", value: 33, opponent: "MIN" },
  { date: "3/1", value: 24, opponent: "OKC" },
  { date: "3/3", value: 29, opponent: "DEN" },
  { date: "3/5", value: 21, opponent: "SAC" },
  { date: "3/7", value: 27, opponent: "HOU" },
  { date: "PROJ", value: 28.2, opponent: "NYK", isProjection: true },
];
